language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get install python-pyaudio python3-pyaudio
# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: 
  - pytest audio/testAudio.py 
